// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANOEtMqeUubdKjrGEDCii7xRPoTgo0V08',
    appId: '1:1020940923995:web:6174982f610cbfe12a3b7e',
    messagingSenderId: '1020940923995',
    projectId: 'exterior-cleaning-marketplace',
    authDomain: 'exterior-cleaning-marketplace.firebaseapp.com',
    storageBucket: 'exterior-cleaning-marketplace.firebasestorage.app',
    measurementId: 'G-23GKHHBLS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5D4NrAp6oRibN_aLPyFG31tUscrj5GkM',
    appId: '1:1020940923995:android:97fbb5461f518d2c2a3b7e',
    messagingSenderId: '1020940923995',
    projectId: 'exterior-cleaning-marketplace',
    storageBucket: 'exterior-cleaning-marketplace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHuhOD-aOZgcW8QI-QweJKoSi2g21WflI',
    appId: '1:1020940923995:ios:2fcc1a11040a60e82a3b7e',
    messagingSenderId: '1020940923995',
    projectId: 'exterior-cleaning-marketplace',
    storageBucket: 'exterior-cleaning-marketplace.firebasestorage.app',
    iosBundleId: 'com.example.exteriorMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHuhOD-aOZgcW8QI-QweJKoSi2g21WflI',
    appId: '1:1020940923995:ios:2fcc1a11040a60e82a3b7e',
    messagingSenderId: '1020940923995',
    projectId: 'exterior-cleaning-marketplace',
    storageBucket: 'exterior-cleaning-marketplace.firebasestorage.app',
    iosBundleId: 'com.example.exteriorMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANOEtMqeUubdKjrGEDCii7xRPoTgo0V08',
    appId: '1:1020940923995:web:4f23f0dd8dffd53c2a3b7e',
    messagingSenderId: '1020940923995',
    projectId: 'exterior-cleaning-marketplace',
    authDomain: 'exterior-cleaning-marketplace.firebaseapp.com',
    storageBucket: 'exterior-cleaning-marketplace.firebasestorage.app',
    measurementId: 'G-17R3YCK6J8',
  );
}
